// coverage:ignore-file
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAghCruPy2cdEO0fFZ9QltjgYtlx8rwbZw',
    appId: '1:33997041371:web:b0481ff9d375bc59b5a6fe',
    messagingSenderId: '33997041371',
    projectId: 'order-manager-1f6bf',
    authDomain: 'order-manager-1f6bf.firebaseapp.com',
    databaseURL: 'https://order-manager-1f6bf-default-rtdb.firebaseio.com',
    storageBucket: 'order-manager-1f6bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjLst3l5nZEsj7rmAvicpgypP3Gs-258',
    appId: '1:33997041371:android:4b91c70665abf461b5a6fe',
    messagingSenderId: '33997041371',
    projectId: 'order-manager-1f6bf',
    databaseURL: 'https://order-manager-1f6bf-default-rtdb.firebaseio.com',
    storageBucket: 'order-manager-1f6bf.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW3F4KfvnAiDXKG18K12gMxntZI1HQ0MI',
    appId: '1:33997041371:ios:07913e8c362f76a6b5a6fe',
    messagingSenderId: '33997041371',
    projectId: 'order-manager-1f6bf',
    databaseURL: 'https://order-manager-1f6bf-default-rtdb.firebaseio.com',
    storageBucket: 'order-manager-1f6bf.firebasestorage.app',
    androidClientId:
        '33997041371-7d9feho9rvp89b4une7b6lpfns3c7jpn.apps.googleusercontent.com',
    iosClientId:
        '33997041371-lfe2egnm0sbe29mhpn75mt9jnevom1cq.apps.googleusercontent.com',
    iosBundleId: 'com.belvinraja.orderManager',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW3F4KfvnAiDXKG18K12gMxntZI1HQ0MI',
    appId: '1:33997041371:ios:07913e8c362f76a6b5a6fe',
    messagingSenderId: '33997041371',
    projectId: 'order-manager-1f6bf',
    databaseURL: 'https://order-manager-1f6bf-default-rtdb.firebaseio.com',
    storageBucket: 'order-manager-1f6bf.firebasestorage.app',
    androidClientId:
        '33997041371-7d9feho9rvp89b4une7b6lpfns3c7jpn.apps.googleusercontent.com',
    iosClientId:
        '33997041371-lfe2egnm0sbe29mhpn75mt9jnevom1cq.apps.googleusercontent.com',
    iosBundleId: 'com.belvinraja.orderManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAghCruPy2cdEO0fFZ9QltjgYtlx8rwbZw',
    appId: '1:33997041371:web:01cd0680e46e5de1b5a6fe',
    messagingSenderId: '33997041371',
    projectId: 'order-manager-1f6bf',
    authDomain: 'order-manager-1f6bf.firebaseapp.com',
    databaseURL: 'https://order-manager-1f6bf-default-rtdb.firebaseio.com',
    storageBucket: 'order-manager-1f6bf.firebasestorage.app',
  );
}
