// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsD_7mm8Ugq6uG9nnUWsWchY1XrQBgwU',
    appId: '1:33997041371:web:0cb29e851add16fcb5a6fe',
    messagingSenderId: '33997041371',
    projectId: 'order-manager-1f6bf',
    authDomain: 'order-manager-1f6bf.firebaseapp.com',
    databaseURL: 'https://order-manager-1f6bf-default-rtdb.firebaseio.com',
    storageBucket: 'order-manager-1f6bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCjLst3l5nZEsj7rmAvicpgypP3Gs-258',
    appId: '1:33997041371:android:e3ebea90d79d28e1b5a6fe',
    messagingSenderId: '33997041371',
    projectId: 'order-manager-1f6bf',
    databaseURL: 'https://order-manager-1f6bf-default-rtdb.firebaseio.com',
    storageBucket: 'order-manager-1f6bf.firebasestorage.app',
  );
}
